# Generated by Django 6.0.6 on 2026-07-19 23:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_categoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nr_cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('nr_telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('ds_biografia', models.TextField(blank=True, null=True)),
                ('tp_foto', models.CharField(blank=True, max_length=255, null=True)),
                ('id_tp_perfil', models.CharField(choices=[('autonomo', 'Autônomo'), ('contratante', 'Contratante')], default='contratante', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_titulo', models.CharField(max_length=50)),
                ('nm_descricao', models.CharField(max_length=150)),
                ('vl_preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nm_area_atendimento', models.CharField(max_length=100)),
                ('nm_disponibilidade', models.CharField(max_length=45)),
                ('st_anuncio', models.BooleanField(default=True)),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_mensagem', models.TextField()),
                ('dt_envio', models.DateTimeField(auto_now_add=True)),
                ('st_visualizacao', models.BooleanField(default=False)),
                ('fk_id_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('fk_id_remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_contratacao', models.DateField()),
                ('st_contratacao', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado'), ('em andamento', 'Em andamento')], default='pendente', max_length=20)),
                ('vl_final_contratacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_execucao', models.DateField()),
                ('hr_execucao', models.TimeField()),
                ('fk_id_autonomo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_prestados', to=settings.AUTH_USER_MODEL)),
                ('fk_id_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_agendamento', models.DateField()),
                ('hr_inicio', models.TimeField()),
                ('hr_final', models.TimeField()),
                ('st_agendamento', models.CharField(blank=True, max_length=45, null=True)),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_id_contratacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contratacao')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_nota', models.IntegerField()),
                ('ds_comentario', models.TextField(blank=True, null=True)),
                ('dt_avaliacao', models.DateField(auto_now_add=True)),
                ('fk_id_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('fk_id_avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('fk_id_contratacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contratacao')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vl_servico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nm_token_api', models.CharField(blank=True, max_length=150, null=True)),
                ('st_pagamento', models.CharField(choices=[('retido', 'Retido'), ('liberado', 'Liberado'), ('bloqueado', 'Bloqueado')], max_length=15)),
                ('dt_declaracao_pagamento', models.DateTimeField(blank=True, null=True)),
                ('fk_id_contratacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contratacao')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_servico', models.CharField(max_length=100)),
                ('ds_servico', models.TextField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(related_name='servicos', to='core.categoria')),
                ('fk_id_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anuncio')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contratacao',
            name='fk_id_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico'),
        ),
    ]
