# Generated by Django 6.0.6 on 2026-07-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tp_foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
    ]
