# Generated by Django 6.0.6 on 2026-08-16 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_tp_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_mensagem', models.TextField()),
                ('dt_envio', models.DateTimeField(auto_now_add=True)),
                ('fk_id_contratacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.contratacao')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
